name: minehostAgent
version: ${project.version}
main: pl.minehostAgent.Main
api-version: 1.13
authors: [Lucyfer, _arturek]
description: Najlepszy hosting serwerów minecraft MINEHOST.PL!
website: https://minehost.pl
